<template>
  <section class="page-section customers-page">
    <div class="page-heading"><div><p class="eyebrow">MASTER DATA</p><h1>Pelanggan</h1><p class="page-description">Kelola pelanggan dan lihat riwayat transaksi POS mereka.</p></div><button class="button button-primary" type="button" @click="openCreate">+ Tambah Pelanggan</button></div>
    <section class="panel"><div class="panel-heading"><div><h2>Daftar Pelanggan</h2><p>{{ customers.length }} pelanggan terdaftar</p></div><input v-model="search" class="customers-search" placeholder="Cari pelanggan" /></div><div class="table-wrap"><table><thead><tr><th>Nama Pelanggan</th><th>Total Transaksi</th><th>Total Belanja</th><th>Utang</th><th>Aksi</th></tr></thead><tbody><tr v-for="customer in filteredCustomers" :key="customer.id"><td>{{ customer.nama }}</td><td>{{ customer.transactionCount || 0 }}</td><td>{{ formatRupiah(customer.totalSpent || 0) }}</td><td>{{ formatRupiah(customer.totalDebt || 0) }}</td><td><button class="action-button view-action" type="button" @click="selectedCustomer = customer">Detail POS</button></td></tr><tr v-if="!filteredCustomers.length"><td colspan="5" class="empty-cell">Belum ada data pelanggan.</td></tr></tbody></table></div></section>
    <div v-if="selectedCustomer" class="modal-backdrop receipt-backdrop" @click.self="selectedCustomer = null"><section class="receipt-modal customer-detail-modal"><header class="receipt-modal-header"><div><p class="eyebrow">RIWAYAT PELANGGAN</p><h2>{{ selectedCustomer.nama }}</h2><p>{{ selectedCustomerTransactions.length }} transaksi POS</p></div><button class="modal-close" type="button" @click="selectedCustomer = null">×</button></header><div class="customer-transaction-list"><div v-for="transaction in selectedCustomerTransactions" :key="transaction.id" class="customer-transaction"><div><strong>{{ transaction.nomor }}</strong><small>{{ formatDate(transaction.tanggal) }} · {{ String(transaction.metodePembayaran || '').toUpperCase() }}</small></div><strong>{{ formatRupiah(transaction.total) }}</strong></div><p v-if="!selectedCustomerTransactions.length" class="empty-cell">Belum ada transaksi POS.</p></div></section></div>
    <div v-if="showForm" class="modal-backdrop" @click.self="showForm = false"><section class="modal-card customer-form-modal"><header class="modal-header"><div><p class="eyebrow">MASTER DATA</p><h2>{{ editing ? 'Edit Pelanggan' : 'Tambah Pelanggan' }}</h2></div><button class="modal-close" type="button" @click="showForm = false">×</button></header><form class="modal-form" @submit.prevent="saveCustomer"><label class="field"><span>Nama Pelanggan</span><input v-model.trim="form.nama" required placeholder="Contoh: Budi" /></label><div class="form-actions"><button class="button button-secondary" type="button" @click="showForm = false">Batal</button><button class="button button-primary" type="submit">Simpan</button></div></form></section></div>
  </section>
</template>

<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { addDoc, collection, doc, getDocs, updateDoc } from 'firebase/firestore'
import Swal from 'sweetalert2'
import { db } from '@/firebase'
import { authState } from '@/auth'
const customers = ref<any[]>([]); const transactions = ref<any[]>([]); const search = ref(''); const selectedCustomer = ref<any|null>(null); const showForm = ref(false); const editing = ref<any|null>(null); const form = ref({ nama: '' }); const base = () => `warungs/${authState.warungId}`
const formatRupiah=(value:number)=>new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(Number(value)||0)
const formatDate=(value:string)=>new Intl.DateTimeFormat('id-ID',{day:'2-digit',month:'short',year:'numeric'}).format(new Date(value))
const filteredCustomers=computed(()=>customers.value.filter((item)=>item.nama.toLowerCase().includes(search.value.toLowerCase())))
const selectedCustomerTransactions=computed(()=>selectedCustomer.value?transactions.value.filter((item)=>item.customerId===selectedCustomer.value.id):[])
const load=async()=>{if(!authState.warungId)return; const [customerSnapshot,saleSnapshot]=await Promise.all([getDocs(collection(db,base(),'customers')),getDocs(collection(db,base(),'sales'))]); const sales=saleSnapshot.docs.map((item)=>({id:item.id,...item.data()})); transactions.value=sales; customers.value=customerSnapshot.docs.map((item)=>{const data:any=item.data(); const own=sales.filter((sale:any)=>sale.customerId===item.id); return {id:item.id,...data,transactionCount:own.length,totalSpent:own.reduce((sum:number,sale:any)=>sum+Number(sale.total||0),0),totalDebt:own.filter((sale:any)=>sale.metodePembayaran==='utang'&&sale.debtStatus!=='paid').reduce((sum:number,sale:any)=>sum+Number(sale.total||0),0)}})}
const openCreate=()=>{editing.value=null; form.value={nama:''}; showForm.value=true}; const saveCustomer=async()=>{if(!form.value.nama.trim()||!authState.warungId)return; if(editing.value) await updateDoc(doc(db,base(),'customers',editing.value.id),{nama:form.value.nama.trim(),updatedAt:new Date().toISOString()}); else await addDoc(collection(db,base(),'customers'),{nama:form.value.nama.trim(),createdAt:new Date().toISOString()}); showForm.value=false; await load(); await Swal.fire({title:'Tersimpan',text:'Data pelanggan berhasil disimpan.',icon:'success',confirmButtonColor:'#2563eb'})}
onMounted(load)
</script>
