<template>
  <section class="page-stack">
    <div class="page-heading"><div><p class="eyebrow">TRANSAKSI PEMBELIAN</p><h1>Purchase Order</h1><p class="page-description">Catat pembelian dari pemasok dan kunci transaksi untuk menambah stok.</p></div><button class="button button-primary" type="button" @click="openForm">＋ Buat PO</button></div>
    <section class="panel product-panel">
      <div class="toolbar"><div><h2>Daftar Purchase Order</h2><p>{{ orders.length }} transaksi</p></div><div class="purchase-filter"><select v-model="statusFilter"><option value="all">Semua status</option><option value="draft">Draft</option><option value="locked">Terkunci</option></select></div></div>
      <div v-if="loading" class="table-state">Memuat transaksi...</div>
      <div v-else-if="!filteredOrders.length" class="table-state"><strong>Belum ada purchase order</strong><span>Buat PO pertama untuk mencatat pembelian barang.</span><button class="button button-primary" type="button" @click="openForm">Buat PO</button></div>
      <div v-else class="table-wrap"><table class="data-table purchase-table"><thead><tr><th>Nomor PO</th><th>Tanggal</th><th>Pemasok</th><th>Item</th><th>Total</th><th>Status</th><th>Aksi</th></tr></thead><tbody><tr v-for="order in filteredOrders" :key="order.id"><td><strong>{{ order.nomor }}</strong><small class="table-subtext">{{ order.catatan || 'Tanpa catatan' }}</small></td><td>{{ formatDate(order.tanggal) }}</td><td>{{ order.pemasok || '-' }}</td><td>{{ order.items.length }} barang</td><td class="price-cell">{{ formatRupiah(order.total) }}</td><td><span :class="['status-badge', order.status === 'locked' ? 'status-locked' : 'status-draft']">{{ order.status === 'locked' ? 'Terkunci' : 'Draft' }}</span></td><td><div class="row-actions"><button v-if="order.status !== 'locked'" class="action-button edit-action" type="button" @click="editOrder(order)">Edit</button><button v-if="order.status !== 'locked'" class="action-button lock-action" type="button" @click="lockOrder(order)">Kunci</button><button class="action-button view-action" type="button" @click="viewOrder(order)">Detail</button></div></td></tr></tbody></table></div>
    </section>
    <div v-if="showForm" class="modal-backdrop" @click.self="closeForm"><section class="modal-card purchase-modal"><header class="modal-header"><div><p class="eyebrow">FORM PEMBELIAN</p><h2>{{ editingOrder ? 'Edit Purchase Order' : 'Buat Purchase Order' }}</h2><p>Tambahkan beberapa barang dalam satu transaksi.</p></div><button class="modal-close" type="button" @click="closeForm">×</button></header><form class="modal-form purchase-form" @submit.prevent="saveOrder"><div class="form-grid"><label class="field"><span>Tanggal Pembelian</span><input v-model="form.tanggal" type="date" required /></label><label class="field"><span>Pemasok</span><input v-model="form.pemasok" placeholder="Nama pemasok (opsional)" /></label><label class="field field-wide"><span>Catatan</span><input v-model="form.catatan" placeholder="Catatan pembelian (opsional)" /></label></div><div class="purchase-items-heading"><div><h3>Daftar Barang</h3><p>Pilih master produk, lalu sesuaikan jumlah dan harga jika diperlukan.</p></div><button class="button button-secondary" type="button" @click="addItem">＋ Tambah Barang</button></div><div class="purchase-items"><div v-for="(item, index) in form.items" :key="item.key" class="purchase-item"><div class="item-number">{{ index + 1 }}</div><label class="field item-product"><span>Produk</span><select v-model="item.produkId" required @change="applyProduct(item)"><option value="" disabled>Pilih produk</option><option v-for="product in products" :key="product.id" :value="product.id">{{ product.nama }} — {{ product.satuan }}</option></select></label><label class="field item-quantity"><span>Jumlah ({{ getProduct(item)?.satuan || 'satuan' }})</span><input v-model.number="item.jumlah" type="number" min="1" required /></label><label class="field item-price"><span>Harga / Satuan</span><input v-model.number="item.hargaSatuan" type="number" min="0" required @input="item.manualPrice = true" /><small v-if="isPriceDifferent(item)" class="price-alert">Harga berbeda dari master ({{ formatRupiah(getProduct(item)?.hargaBeli) }})</small></label><div class="item-total">{{ formatRupiah(item.jumlah * item.hargaSatuan) }}</div><button v-if="form.items.length > 1" class="remove-item" type="button" aria-label="Hapus barang" @click="removeItem(index)">×</button></div></div><div class="purchase-total"><span>Total Harga PO</span><strong>{{ formatRupiah(formTotal) }}</strong></div><footer class="modal-footer"><button class="button button-secondary" type="button" @click="closeForm">Batal</button><button class="button button-primary" type="submit" :disabled="saving">{{ saving ? 'Menyimpan...' : 'Simpan Draft' }}</button></footer></form></section></div>
    <div v-if="detailOrder" class="modal-backdrop" @click.self="detailOrder = null"><section class="modal-card"><header class="modal-header"><div><p class="eyebrow">DETAIL TRANSAKSI</p><h2>{{ detailOrder.nomor }}</h2><p>{{ formatDate(detailOrder.tanggal) }} · {{ detailOrder.status === 'locked' ? 'Terkunci' : 'Draft' }}</p></div><button class="modal-close" type="button" @click="detailOrder = null">×</button></header><div class="modal-form"><div v-for="item in detailOrder.items" :key="item.produkId" class="detail-row"><span>{{ item.nama }} <small>{{ item.jumlah }} {{ item.satuan }}</small></span><strong>{{ formatRupiah(item.jumlah * item.hargaSatuan) }}</strong></div><div class="purchase-total"><span>Total</span><strong>{{ formatRupiah(detailOrder.total) }}</strong></div></div></section></div>
  </section>
</template>

<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { useRouter } from 'vue-router'
import { addDoc, collection, doc, getDocs, runTransaction, updateDoc } from 'firebase/firestore'
import Swal from 'sweetalert2'
import { db } from '@/firebase'
import { authState } from '@/auth'

const router = useRouter()
const orders = ref<any[]>([])
const products = ref<any[]>([])
const loading = ref(true)
const saving = ref(false)
const showForm = ref(false)
const editingOrder = ref<any | null>(null)
const detailOrder = ref<any | null>(null)
const statusFilter = ref('all')
const form = ref<any>({ tanggal: new Date().toISOString().slice(0, 10), pemasok: '', catatan: '', items: [] })

const filteredOrders = computed(() => statusFilter.value === 'all' ? orders.value : orders.value.filter((order) => order.status === statusFilter.value))
const formTotal = computed(() => form.value.items.reduce((total: number, item: any) => total + (Number(item.jumlah) || 0) * (Number(item.hargaSatuan) || 0), 0))
const getProduct = (item: any) => products.value.find((product) => product.id === item.produkId)
const formatRupiah = (value: number | string) => value ? new Intl.NumberFormat('id-ID', { style: 'currency', currency: 'IDR', maximumFractionDigits: 0 }).format(Number(value)) : 'Rp 0'
const formatDate = (value: string) => value ? new Intl.DateTimeFormat('id-ID', { dateStyle: 'medium' }).format(new Date(`${value}T00:00:00`)) : '-'
const isPriceDifferent = (item: any) => { const product = getProduct(item); return Boolean(product && item.manualPrice && Number(item.hargaSatuan) !== Number(product.hargaBeli)) }
const newItem = () => ({ key: `${Date.now()}-${Math.random()}`, produkId: '', jumlah: 1, hargaSatuan: 0, manualPrice: false })
const addItem = () => form.value.items.push(newItem())
const removeItem = (index: number) => form.value.items.splice(index, 1)
const applyProduct = (item: any) => { const product = getProduct(item); if (product) { item.hargaSatuan = Number(product.hargaBeli) || 0; item.manualPrice = false } }
const basePath = () => `warungs/${authState.warungId}`

const loadData = async () => { if (!authState.warungId) return; loading.value = true; try { const [productSnapshot, orderSnapshot] = await Promise.all([getDocs(collection(db, basePath(), 'produk')), getDocs(collection(db, basePath(), 'purchaseOrders'))]); products.value = productSnapshot.docs.map((item) => ({ id: item.id, ...item.data() })); orders.value = orderSnapshot.docs.map((item) => ({ id: item.id, ...item.data() } as any)).sort((a: any, b: any) => String(b.createdAt || '').localeCompare(String(a.createdAt || ''))) } finally { loading.value = false } }
const openForm = () => router.push('/pembelian/baru')
const editOrder = (order: any) => router.push(`/pembelian/${order.id}/edit`)
const closeForm = () => { showForm.value = false; editingOrder.value = null }
const saveOrder = async () => { if (!authState.warungId || form.value.items.some((item: any) => !item.produkId || item.jumlah < 1)) return; saving.value = true; try { const items = form.value.items.map((item: any) => { const product = getProduct(item); return { produkId: product.id, nama: product.nama, satuan: product.satuan, unitPerSatuan: Number(product.unit) || 1, jumlah: Number(item.jumlah), hargaSatuan: Number(item.hargaSatuan), subtotal: Number(item.jumlah) * Number(item.hargaSatuan) } }); const payload = { tanggal: form.value.tanggal, pemasok: form.value.pemasok.trim(), catatan: form.value.catatan.trim(), items, total: formTotal.value, status: 'draft', createdAt: editingOrder.value?.createdAt || new Date().toISOString(), updatedAt: new Date().toISOString() }; if (editingOrder.value) await updateDoc(doc(db, basePath(), 'purchaseOrders', editingOrder.value.id), payload); else await addDoc(collection(db, basePath(), 'purchaseOrders'), payload); closeForm(); await loadData(); await Swal.fire({ title: 'Draft tersimpan', icon: 'success', timer: 1300, showConfirmButton: false }) } finally { saving.value = false } }
const lockOrder = async (order: any) => { const confirm = await Swal.fire({ title: 'Kunci purchase order?', text: 'Setelah dikunci, PO tidak dapat diedit dan stok akan bertambah dalam pcs.', icon: 'warning', showCancelButton: true, confirmButtonText: 'Ya, kunci transaksi', cancelButtonText: 'Batal', confirmButtonColor: '#2563eb' }); if (!confirm.isConfirmed || !authState.warungId) return; try { await runTransaction(db, async (transaction) => { const orderRef = doc(db, basePath(), 'purchaseOrders', order.id); const fresh = await transaction.get(orderRef); if (!fresh.exists() || fresh.data().status === 'locked') return; for (const item of order.items) { const productRef = doc(db, basePath(), 'produk', item.produkId); const product = await transaction.get(productRef); const currentStock = Number(product.data()?.stokPcs) || 0; transaction.update(productRef, { stokPcs: currentStock + (Number(item.jumlah) * Number(item.unitPerSatuan)), updatedAt: new Date().toISOString() }) } transaction.update(orderRef, { status: 'locked', lockedAt: new Date().toISOString() }) }); await loadData(); await Swal.fire({ title: 'Transaksi dikunci', text: 'Stok produk berhasil diperbarui.', icon: 'success', confirmButtonColor: '#2563eb' }) } catch (error: any) { await Swal.fire({ title: 'Gagal mengunci PO', text: error?.message || 'Coba lagi.', icon: 'error', confirmButtonColor: '#2563eb' }) } }
const viewOrder = (order: any) => { detailOrder.value = order }
onMounted(loadData)
</script>
